// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS28nf5ie1vLXC3FPHfIUGnDWCSqNyKCM',
    appId: '1:904591149899:web:ca50c7b2ef37d3107af6ce',
    messagingSenderId: '904591149899',
    projectId: 'uas-fintech',
    authDomain: 'uas-fintech.firebaseapp.com',
    storageBucket: 'uas-fintech.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMXPduDla0WxdsRYKywQhp4Ymfmeypw-k',
    appId: '1:904591149899:android:9e340c5fa0553ac07af6ce',
    messagingSenderId: '904591149899',
    projectId: 'uas-fintech',
    storageBucket: 'uas-fintech.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_kOOauhXHYtw0QVpWR4-BbZSfUuTE454',
    appId: '1:904591149899:ios:e74d1908b59d70897af6ce',
    messagingSenderId: '904591149899',
    projectId: 'uas-fintech',
    storageBucket: 'uas-fintech.firebasestorage.app',
    iosBundleId: 'com.example.uasFintech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_kOOauhXHYtw0QVpWR4-BbZSfUuTE454',
    appId: '1:904591149899:ios:e74d1908b59d70897af6ce',
    messagingSenderId: '904591149899',
    projectId: 'uas-fintech',
    storageBucket: 'uas-fintech.firebasestorage.app',
    iosBundleId: 'com.example.uasFintech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS28nf5ie1vLXC3FPHfIUGnDWCSqNyKCM',
    appId: '1:904591149899:web:f1f8256c6966b6eb7af6ce',
    messagingSenderId: '904591149899',
    projectId: 'uas-fintech',
    authDomain: 'uas-fintech.firebaseapp.com',
    storageBucket: 'uas-fintech.firebasestorage.app',
  );
  
}